### ISSUE TITLE
Could you help upgrade the vulnerble dependency in vp-suite

### ISSUE THREAD

**Issue by JoeGardner000** [AIS-Bonn/vp-suite#33]
Hi, @Flunzmas , I'd like to report a vulnerability issue in **vp-suite_0.0.9**.
### Issue Description
I noticed that **vp-suite_0.0.9** directly depends on **opencv-python_4.5.4.60**.
However, **opencv-python_4.5.4.60** sufferes from the vulnerabilites which the C libraries exposed as following dependency graph shows. Refer to [issue](https://github.com/opencv/opencv-python/issues/646).

### Dependency Graph between Python and Shared Libraries
![image (1)](https://user-images.githubusercontent.com/103017573/161750044-0a4c6917-4dbc-4a63-a57e-3c0af64bbf6e.png)

### Suggested Vulnerability Patch Versions
**opencv-python** has upgraded these vulnerable C libraries to patch versions in release ***4.5.5.64***. 

Python build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Python projects.
Could you please upgrade this vulnerable dependency?

Thanks for your help~
Best regards,
JoeGardner

**Comment by Flunzmas** [comment]
Hey there, sorry for the time passed. Will upgrade the dependency shortly.
